(()=>{
'use strict';
const facts=window.KASHIKIN_FACTS||[],sources=window.KASHIKIN_SOURCES||{};
const K='kashikinStudyV1';
const defaultState={stats:{},wrong:[],bookmarks:[],sessions:[],settings:{daily:20,pass:31,theme:'system'},lastMode:null};
let state=loadState(),bank=[],session=null,timerHandle=null;
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function loadState(){try{return {...defaultState,...JSON.parse(localStorage.getItem(K)||'{}'),settings:{...defaultState.settings,...(JSON.parse(localStorage.getItem(K)||'{}').settings||{})}}}catch{return structuredClone(defaultState)}}
function save(){localStorage.setItem(K,JSON.stringify(state))}
function hash(s){let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}
function rng(seed){let x=seed||123456789;return()=>{x^=x<<13;x^=x>>>17;x^=x<<5;return(x>>>0)/4294967296}}
function shuffle(a,r){a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(r()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function generateBank(){const by={};facts.forEach(f=>(by[f.category]??=[]).push(f));const result=[];let serial=1;Object.entries(by).forEach(([cat,arr],ci)=>{const seen=new Set(),r=rng(hash(cat));let tries=0;while(seen.size<100&&tries<10000){tries++;const askCorrect=seen.size%2===0;const chosen=shuffle(arr,r).slice(0,4);const target=Math.floor(r()*4);const opts=chosen.map((f,i)=>{const truth=askCorrect?(i===target):(i!==target);return {factId:f.id,text:truth?f.trueText:f.falseText,truth,wrongQuote:truth?'':f.wrongQuote,correction:f.correction,explanation:f.explanation,source:f.source}});const ordered=shuffle(opts,r);const correct=ordered.findIndex(o=>askCorrect?o.truth:!o.truth);const sig=(askCorrect?'T':'F')+'|'+ordered.map(o=>o.factId+(o.truth?'1':'0')).join('|');if(seen.has(sig))continue;seen.add(sig);const base=chosen[0];result.push({id:'Q'+String(serial++).padStart(4,'0'),section:base.section,category:cat,topic:base.topic,ask:askCorrect?'correct':'incorrect',prompt:`次の記述のうち、${askCorrect?'適切なもの':'適切でないもの'}を1つ選びなさい。`,options:ordered,correct});}}
);return result}
bank=generateBank();
const cats=[...new Set(facts.map(f=>f.category))];
function setTheme(){const t=state.settings.theme;if(t==='system'){document.documentElement.dataset.theme=matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'}else document.documentElement.dataset.theme=t}
setTheme();matchMedia('(prefers-color-scheme: dark)').addEventListener?.('change',setTheme);
function show(id){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));$(id).classList.add('active');scrollTo({top:0,behavior:'instant'})}
function overall(){const vals=Object.values(state.stats);const answered=vals.reduce((s,v)=>s+(v.attempts||0),0),correct=vals.reduce((s,v)=>s+(v.correct||0),0);return {answered,correct,rate:answered?Math.round(correct/answered*100):0}}
function streak(){const days=[...new Set(state.sessions.map(x=>x.date))].sort().reverse();if(!days.length)return 0;let n=0,d=new Date();for(;;){const k=d.toISOString().slice(0,10);if(days.includes(k)){n++;d.setDate(d.getDate()-1)}else if(n===0){d.setDate(d.getDate()-1);if(!days.includes(d.toISOString().slice(0,10)))break}else break}return n}
function todayCount(){const d=new Date().toISOString().slice(0,10);return state.sessions.filter(x=>x.date===d).reduce((s,x)=>s+x.total,0)}
function home(){clearTimer();const o=overall(),done=todayCount();$('home').innerHTML=`
<div class="card hero"><div class="heroTop"><div><div class="muted">今日の進捗</div><div class="heroScore">${Math.min(done,state.settings.daily)}<small style="font-size:18px"> / ${state.settings.daily}問</small></div><div class="muted">連続学習 ${streak()}日 ・ 総正答率 ${o.rate}%</div></div><div style="font-size:42px">📘</div></div><button class="btn full" style="margin-top:14px;background:white;color:#1948c5;border:0" onclick="App.startDaily()">今日のおすすめを始める</button></div>
<div class="stats3"><div class="stat"><b>${bank.length}</b><span>収録問題</span></div><div class="stat"><b>${o.answered}</b><span>回答回数</span></div><div class="stat"><b>${state.wrong.length}</b><span>要復習</span></div></div>
<div class="sectionTitle">学習モード</div><div class="grid">
<button class="menu" onclick="App.openCategories()"><span class="emoji">📚</span><b>分野別</b><span class="muted">20分野から選択</span></button>
<button class="menu" onclick="App.setupRandom()"><span class="emoji">🎲</span><b>ランダム</b><span class="muted">全分野から出題</span></button>
<button class="menu" onclick="App.startMock()"><span class="emoji">📝</span><b>本試験形式</b><span class="muted">50問・120分</span></button>
<button class="menu" onclick="App.openReview()"><span class="emoji">🔁</span><b>復習</b><span class="muted">間違い・ブックマーク</span></button></div>
<div class="sectionTitle">最近の成績</div><div class="card">${recentSessions()}</div>
<div class="notice">本試験形式は、第20回の科目構成（法令27問・貸付実務15問・資金需要者保護5問・財務会計3問）に合わせ、各科目で「適切なもの」を先に、「適切でないもの」を後に並べます。</div>`;show('home')}
function recentSessions(){if(!state.sessions.length)return '<div class="muted">まだ学習履歴がありません。</div>';return state.sessions.slice(-5).reverse().map(s=>`<div style="display:flex;justify-content:space-between;padding:8px 0;border-bottom:1px solid var(--line)"><span>${esc(s.label)}<small class="muted"> ${s.date}</small></span><b>${s.score}/${s.total}</b></div>`).join('')}
function openCategories(){const counts={};bank.forEach(q=>counts[q.category]=(counts[q.category]||0)+1);$('categories').innerHTML=`<div class="row"><button class="btn" onclick="App.home()">← ホーム</button><div></div></div><div class="sectionTitle">分野を選ぶ</div><div class="categoryList">${cats.map(c=>{const st=categoryStat(c);return `<button class="catBtn" onclick="App.setupCategory('${esc(c)}')"><div><b>${esc(c)}</b><span>${counts[c]}問 ・ 正答率 ${st.rate}%</span></div><strong>›</strong></button>`}).join('')}</div>`;show('categories')}
function categoryStat(c){let a=0,ok=0;bank.filter(q=>q.category===c).forEach(q=>{const s=state.stats[q.id];if(s){a+=s.attempts||0;ok+=s.correct||0}});return {a,ok,rate:a?Math.round(ok/a*100):0}}
function setupCategory(c){setup({type:'category',category:c,label:c})}
function setupRandom(){setup({type:'random',label:'ランダム'})}
function setup(cfg){$('setup').innerHTML=`<button class="btn" onclick="App.home()">← 戻る</button><div class="card" style="margin-top:12px"><div class="pill">${esc(cfg.label)}</div><h2>出題設定</h2><label class="formLabel">問題数</label><select id="count" class="field"><option>10</option><option selected>20</option><option>30</option><option>50</option><option>100</option></select><label class="formLabel">解答後の表示</label><select id="feedbackMode" class="field"><option value="instant">すぐ正誤と解説を表示</option><option value="end">最後にまとめて採点</option></select><button class="btn primary full" style="margin-top:16px" onclick='App.beginSetup(${JSON.stringify(cfg)})'>開始</button></div>`;show('setup')}
function beginSetup(cfg){const n=Number($('count').value),instant=$('feedbackMode').value==='instant';let pool=cfg.type==='category'?bank.filter(q=>q.category===cfg.category):bank;startSession(pick(pool,n,Date.now()),{label:cfg.label,instant,timed:false})}
function pick(pool,n,seed){return shuffle(pool,rng(seed)).slice(0,Math.min(n,pool.length))}
function startDaily(){const date=new Date().toISOString().slice(0,10),r=rng(hash(date));const weighted=[];cats.forEach(c=>{const st=categoryStat(c),w=st.a===0?2:Math.max(1,Math.round((100-st.rate)/20));for(let i=0;i<w;i++)weighted.push(c)});const qs=[],used=new Set();while(qs.length<state.settings.daily&&used.size<bank.length){const c=weighted[Math.floor(r()*weighted.length)],p=bank.filter(q=>q.category===c&&!used.has(q.id));if(!p.length)continue;const q=p[Math.floor(r()*p.length)];used.add(q.id);qs.push(q)}startSession(qs,{label:'今日のおすすめ',instant:true,timed:false})}
function startMock(){const seed=Date.now(),r=rng(seed),counts={1:27,2:15,3:5,4:3},qs=[];Object.entries(counts).forEach(([sec,n])=>{qs.push(...pick(bank.filter(q=>q.section===Number(sec)),n,Math.floor(r()*1e9))) });qs.sort((a,b)=>a.section-b.section||(a.ask===b.ask?cats.indexOf(a.category)-cats.indexOf(b.category):(a.ask==='correct'?-1:1)));startSession(qs,{label:'本試験形式',instant:false,timed:true,duration:120*60})}
function startSession(qs,opt){session={questions:qs,index:0,answers:Array(qs.length).fill(null),checked:Array(qs.length).fill(false),...opt,started:Date.now(),endAt:opt.timed?Date.now()+opt.duration*1000:null};state.lastMode={ids:qs.map(q=>q.id),opt:{label:opt.label,instant:opt.instant,timed:opt.timed,duration:opt.duration}};save();renderQuiz();show('quiz');if(opt.timed)startTimer()}
function renderQuiz(){const q=session.questions[session.index],ans=session.answers[session.index],checked=session.checked[session.index];$('quiz').innerHTML=`<div class="card"><div class="topbar"><button class="btn" style="padding:8px 10px" onclick="App.confirmQuit()">終了</button><span class="pill">${esc(q.category)}</span><span id="timer" class="timer">${session.timed?'120:00':`${session.index+1}/${session.questions.length}`}</span></div><div class="progress"><i style="width:${(session.index+1)/session.questions.length*100}%"></i></div><div class="topbar"><span class="muted">問 ${session.index+1} / ${session.questions.length}</span><button class="bookmark ${state.bookmarks.includes(q.id)?'on':''}" onclick="App.toggleBookmark('${q.id}')">★</button></div><div class="question">${esc(q.prompt)}</div>${q.options.map((o,i)=>`<button class="option ${ans===i?'selected':''} ${checked?(i===q.correct?'correct':(ans===i?'wrong':'')):''}" ${checked?'disabled':''} onclick="App.choose(${i})"><span class="num">${i+1}</span><span>${esc(o.text)}</span></button>`).join('')}${checked?feedbackHtml(q,ans):''}<div class="navActions"><button class="btn" ${session.index===0?'disabled':''} onclick="App.prev()">前へ</button><button class="btn primary" onclick="App.next()">${session.index===session.questions.length-1?'採点する':'次へ'}</button></div></div>`;if(session.timed)updateTimer()}
function feedbackHtml(q,ans){const ok=ans===q.correct;return `<div class="feedback ${ok?'ok':'ng'}">${ok?'正解':'不正解'}　正解は ${q.correct+1}</div><div class="explanations">${q.options.map((o,i)=>optionExp(o,i,q.correct)).join('')}</div>`}
function optionExp(o,i,correct){const src=sources[o.source]||{};return `<div class="exp"><div class="expHead"><span>選択肢 ${i+1}</span><span class="${i===correct?'good':''}">${o.truth?'正しい記述':'誤った記述'}</span></div>${o.truth?`<div class="correctText">${esc(o.explanation)}</div>`:`<div class="quote">「${esc(o.wrongQuote)}」</div><div class="correctText"><b>正しい内容</b><br>${esc(o.correction)}</div><div class="muted" style="margin-top:7px">${esc(o.explanation)}</div>`}<div class="source">根拠：${src.url?`<a href="${esc(src.url)}" target="_blank" rel="noopener">${esc(src.label)}</a>`:esc(src.label||'収録データ')}</div></div>`}
function choose(i){if(session.checked[session.index])return;session.answers[session.index]=i;if(session.instant){session.checked[session.index]=true;recordAttempt(session.questions[session.index],i)}renderQuiz()}
function next(){if(session.answers[session.index]===null){toast('選択肢を選んでください');return}if(!session.instant&&!session.checked[session.index]){}if(session.instant&&!session.checked[session.index]){session.checked[session.index]=true;recordAttempt(session.questions[session.index],session.answers[session.index]);renderQuiz();return}if(session.index===session.questions.length-1){finish();return}session.index++;renderQuiz()}
function prev(){if(session.index>0){session.index--;renderQuiz()}}
function recordAttempt(q,ans){const s=state.stats[q.id]||{attempts:0,correct:0,last:0};s.attempts++;if(ans===q.correct)s.correct++;s.last=Date.now();state.stats[q.id]=s;if(ans!==q.correct){if(!state.wrong.includes(q.id))state.wrong.push(q.id)}else if(s.attempts>=2&&s.correct/s.attempts>=.7){state.wrong=state.wrong.filter(x=>x!==q.id)}save()}
function finish(){clearTimer();if(!session.instant){session.questions.forEach((q,i)=>recordAttempt(q,session.answers[i]));session.checked.fill(true)}const score=session.questions.reduce((s,q,i)=>s+(session.answers[i]===q.correct),0),total=session.questions.length;state.sessions.push({date:new Date().toISOString().slice(0,10),label:session.label,score,total,at:Date.now()});state.sessions=state.sessions.slice(-100);save();renderResult(score,total);show('result')}
function renderResult(score,total){const pass=total===50?score>=state.settings.pass:score/total>=state.settings.pass/50;const by={};session.questions.forEach((q,i)=>{by[q.category]??={ok:0,total:0};by[q.category].total++;if(session.answers[i]===q.correct)by[q.category].ok++});const weak=Object.entries(by).sort((a,b)=>a[1].ok/a[1].total-b[1].ok/b[1].total).slice(0,3);$('result').innerHTML=`<div class="card"><span class="pill">結果</span><div class="resultScore">${score}<small style="font-size:22px"> / ${total}</small></div><div class="judge ${pass?'good':'bad'}">${pass?'合格圏':'要復習'}</div><div class="muted" style="text-align:center;margin:5px">${total===50?`合格圏設定 ${state.settings.pass}/50`: `正答率 ${Math.round(score/total*100)}%`}</div></div><div class="card"><h3>分野別</h3>${Object.entries(by).map(([c,v])=>`<div class="barRow"><div class="barLabel"><b>${esc(c)}</b><span>${v.ok}/${v.total}（${Math.round(v.ok/v.total*100)}%）</span></div><div class="bar"><i style="width:${v.ok/v.total*100}%"></i></div></div>`).join('')}</div><div class="card"><h3>学習分析</h3><div class="analysisBox">${analysisText(weak)}</div><div class="row" style="margin-top:13px"><button class="btn" onclick="App.retryWrong()">間違いだけ復習</button><button class="btn primary" onclick="App.retrySame()">同じ問題を解く</button></div></div><div class="sectionTitle">全問題の回答・正誤</div>${session.questions.map((q,i)=>answerItem(q,i)).join('')}<button class="btn full" onclick="App.home()">ホームへ</button>`}
function analysisText(weak){if(!weak.length)return 'データがありません。';return `優先して復習したい分野は、<b>${weak.map(([c,v])=>`${esc(c)}（${Math.round(v.ok/v.total*100)}%）`).join('、')}</b>です。誤った選択肢の「誤った記述」と「正しい内容」を対にして覚え、数字・期限・主体を重点的に確認してください。`}
function answerItem(q,i){const ans=session.answers[i],ok=ans===q.correct;return `<div class="answerItem ${ok?'ok':'ng'}"><div class="answerHead"><b>問${i+1}　${esc(q.category)}</b><span class="mark">${ok?'正解':'不正解'}</span></div><div class="muted" style="margin-top:6px">あなた：${ans===null?'未回答':ans+1} ／ 正解：${q.correct+1}</div><div style="margin-top:8px;line-height:1.55">${esc(q.options[ans]?.text||'未回答')}</div><details><summary>全選択肢の解説</summary>${q.options.map((o,j)=>optionExp(o,j,q.correct)).join('')}</details></div>`}
function retryWrong(){const qs=session.questions.filter((q,i)=>session.answers[i]!==q.correct);if(!qs.length){toast('間違えた問題はありません');return}startSession(qs,{label:'直前の間違い復習',instant:true,timed:false})}
function retrySame(){startSession(session.questions,{label:session.label+'（再挑戦）',instant:session.instant,timed:session.timed,duration:session.duration})}
function openReview(){const wrongQs=state.wrong.map(id=>bank.find(q=>q.id===id)).filter(Boolean),bookQs=state.bookmarks.map(id=>bank.find(q=>q.id===id)).filter(Boolean);$('review').innerHTML=`<button class="btn" onclick="App.home()">← ホーム</button><div class="card" style="margin-top:12px"><h2>復習</h2><button class="catBtn" onclick="App.startReview('wrong')"><div><b>間違えた問題</b><span>${wrongQs.length}問</span></div><strong>›</strong></button><button class="catBtn" style="margin-top:9px" onclick="App.startReview('bookmark')"><div><b>ブックマーク</b><span>${bookQs.length}問</span></div><strong>›</strong></button></div><div class="card"><h3>データ管理</h3><div class="row"><button class="btn" onclick="App.exportData()">書き出し</button><label class="btn" style="text-align:center">読み込み<input type="file" accept="application/json" hidden onchange="App.importData(this.files[0])"></label></div></div>`;show('review')}
function startReview(type){const ids=type==='wrong'?state.wrong:state.bookmarks,qs=ids.map(id=>bank.find(q=>q.id===id)).filter(Boolean);if(!qs.length){toast('対象の問題がありません');return}startSession(pick(qs,Math.min(50,qs.length),Date.now()),{label:type==='wrong'?'間違い復習':'ブックマーク',instant:true,timed:false})}
function toggleBookmark(id){state.bookmarks=state.bookmarks.includes(id)?state.bookmarks.filter(x=>x!==id):[...state.bookmarks,id];save();renderQuiz()}
function showSettings(){$('sheet').innerHTML=`<div class="sheetTitle">設定</div><label class="formLabel">1日の目標問題数</label><select id="dailySetting" class="field"><option ${state.settings.daily===10?'selected':''}>10</option><option ${state.settings.daily===20?'selected':''}>20</option><option ${state.settings.daily===30?'selected':''}>30</option><option ${state.settings.daily===50?'selected':''}>50</option></select><label class="formLabel">本試験モードの合格圏</label><select id="passSetting" class="field">${[30,31,32,33,34,35].map(n=>`<option ${state.settings.pass===n?'selected':''} value="${n}">${n}/50</option>`).join('')}</select><label class="formLabel">表示テーマ</label><select id="themeSetting" class="field"><option value="system" ${state.settings.theme==='system'?'selected':''}>iPhone設定に合わせる</option><option value="light" ${state.settings.theme==='light'?'selected':''}>ライト</option><option value="dark" ${state.settings.theme==='dark'?'selected':''}>ダーク</option></select><button class="btn primary full" style="margin-top:16px" onclick="App.saveSettings()">保存</button><button class="btn danger full" style="margin-top:9px" onclick="App.resetAll()">学習履歴をすべて消去</button><div class="notice" style="margin-top:14px">問題はすべて端末内に収録され、回答履歴もこのiPhone内のSafariデータに保存されます。</div>`;$('modal').classList.remove('hidden')}
function saveSettings(){state.settings.daily=Number($('dailySetting').value);state.settings.pass=Number($('passSetting').value);state.settings.theme=$('themeSetting').value;save();setTheme();closeModal();home();toast('設定を保存しました')}
function closeModal(){$('modal').classList.add('hidden')}
function resetAll(){if(!confirm('学習履歴、間違い、ブックマークをすべて消去しますか？'))return;state=structuredClone(defaultState);save();setTheme();closeModal();home()}
function exportData(){const b=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='kashikin-study-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function importData(f){if(!f)return;const r=new FileReader();r.onload=()=>{try{const d=JSON.parse(r.result);state={...defaultState,...d,settings:{...defaultState.settings,...(d.settings||{})}};save();home();toast('復元しました')}catch{alert('バックアップファイルを読み込めませんでした')}};r.readAsText(f)}
function confirmQuit(){if(confirm('この学習を終了してホームへ戻りますか？'))home()}
function startTimer(){clearTimer();timerHandle=setInterval(()=>{updateTimer();if(Date.now()>=session.endAt){clearTimer();alert('試験時間が終了しました。採点します。');finish()}},1000)}
function updateTimer(){const el=$('timer');if(!el||!session?.timed)return;const sec=Math.max(0,Math.ceil((session.endAt-Date.now())/1000));el.textContent=`${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`}
function clearTimer(){if(timerHandle){clearInterval(timerHandle);timerHandle=null}}
function toast(s){const el=$('toast');el.textContent=s;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1800)}
window.App={home,openCategories,setupCategory,setupRandom,beginSetup,startDaily,startMock,choose,next,prev,toggleBookmark,confirmQuit,retryWrong,retrySame,openReview,startReview,showSettings,saveSettings,closeModal,resetAll,exportData,importData};
if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
home();
})();